import { GAME_PHASE } from "../../enums/GameState";
import { PieceFormat, Player } from "../../types/gameTypes";

export enum ACTIONS {
  SET_GAMEMODE = "SET_GAMEMODE",
  ROLL_DICE = "ROLL_DICE",
  SELECT_PIECE = "SELECT_PIECE",
  MOVE_PIECE = "MOVE_PIECE",
  SET_INITIAL_PLAYERS = "SET_INTIAL_PLAYERS",
  SET_INITAL_ROLL = "SET_INITAL_ROLL",
  SET_CURRENT_PLAYER = "SET_CURRENT_PLAYER",
  END_TURN = "END_TURN",
  SET_BOARD = "SET_BOARD",
  SET_POSSIBLE_MOVES = "SET_POSSIBLE_MOVES",
  SET_HIT_PIECE = "SET_HIT_PIECE",
  SET_IS_ROLLING = "SET_IS_ROLLING",
  SET_GAME_PHASE = "SET_GAME_PHASE",
  START_INITIAL_DICE_ROLL = "GET_INTIAL_DICE_ROLL",
  RESET_GAME = "RESET_GAME",
  START_ROLLING_ANIMATION = "START_ROLLING_ANIMATION",
  STOP_ROLLING_ANIMATION = "STOP_ROLLING_ANIMATION",
}

export type GameAction =
  | { type: ACTIONS.ROLL_DICE }
  | { type: ACTIONS.SELECT_PIECE; payload: PieceFormat }
  | { type: ACTIONS.MOVE_PIECE; payload: { from: number; to: number } }
  | { type: ACTIONS.SET_INITIAL_PLAYERS; payload: { whitePlayer: Player; blackPlayer: Player } }
  | { type: ACTIONS.SET_GAMEMODE; payload: GAME_MODE }
  | { type: ACTIONS.SET_GAME_PHASE; payload: GAME_PHASE }
  | { type: ACTIONS.START_INITIAL_DICE_ROLL }
  | { type: ACTIONS.SET_CURRENT_PLAYER }
  | { type: ACTIONS.RESET_GAME }
  | { type: ACTIONS.START_ROLLING_ANIMATION }
  | { type: ACTIONS.STOP_ROLLING_ANIMATION };

export enum GAME_MODE {
  SINGLEPLAYER = "SINGLEPLAYER",
  COMPUTER = "COMPUTER",
  MULTIPLAYER = "MULTIPLAYER",
}
