export enum GAME_STATE {
  WAITING_FOR_GAMEMODE = "WAITING_FOR_GAMEMODE",
  WAITING_FOR_PLAYER_CONFIGURATION = "WAITING_FOR_PLAYERS",
  WAITING_FOR_INITIAL_ROLL = "WAITING_FOR_INITIAL_ROLL",
  INITIAL_ROLL = "INITIAL_ROLL",
  GAME_RUNNING = "GAME_RUNNING",
  GAME_OVER = "GAME_OVER",
}
