export enum GAME_PHASE {
  SETUP = "SETUP",
  INITIAL_ROLL = "INITIAL_ROLL",
  PLAYING = "PLAYING",
  GAME_OVER = "GAME_OVER",
}

export enum TURN_PHASE {
  WAITING_FOR_ROLL = "WAITING_FOR_ROLL",
  MOVING = "MOVING",
  // TURN_COMPLETE = "TURN_COMPLETE",
}
